---
title: "Football Kick Project"
output: html_document
date: "2023-07-14"
---

# Setting up libraries
```{r}
library(zoo)
library(pracma)
library(signal)
library(tidyverse)
library(gsignal)
library(readxl)
library(patchwork)
library(magrittr)
```

# EMG processing

## Setup plotting and load data
```{r}
data_mvc_bf <- read_excel("R_BFMVC.xlsx") |>
  rename(time = `X [s]`, signal = `R BICEPS FEMORIS: EMG 2 [V]`)
data_mvc_rf <- read_excel("R_RFMVC.xlsx") |>
  rename(time = `X [s]`, signal = `R RECTUS FEMORIS: EMG 1 [V]`)
data_mvt <- read_excel("EMG_MOVEMENT.xlsx") |>
   rename(time = `X [s]`,
          signal_rf = `R RECTUS FEMORIS: EMG 1 [V]`,
          signal_bf = `R BICEPS FEMORIS: EMG 2 [V]`
    )
```



## Raw EMG signals
```{r}
gg_mvc_bf_raw <- ggplot(data_mvc_bf, aes(time, signal)) +
  geom_line(color = "blue") +
  labs(x = "Time", 
       y = "Amplitude (mV)", 
       title = "EMG MVC Biceps Femoris Raw") +
  theme_light()

gg_mvc_rf_raw <- ggplot(data_mvc_rf, aes(time, signal)) +
  geom_line(color = "blue") +
  labs(x = "Time", 
       y = "Amplitude (mV)", 
       title = "EMG MVC Rectus Femoris Raw") +
  theme_light()

gg_mvt_bf_raw <- ggplot(data_mvt, aes(time, signal_bf)) +
  geom_line(color = "blue") +
  labs(x = "Time", 
       y = "Amplitude (mV)", 
       title = "EMG Movement Biceps Femoris Raw") +
  theme_light()

gg_mvt_rf_raw <- ggplot(data_mvt, aes(time, signal_rf)) +
  geom_line(color = "blue") +
  labs(x = "Time", 
       y = "Amplitude (mV)", 
       title = "EMG Movement Rectus Femoris Raw") +
  theme_light()

```

## Filter EMG data
```{r}
fs <- 2160
lowcut <- 20
highcut <- 450
order <- 4

# Design a Butterworth filter
bf <- butter(order, c(lowcut, highcut)/(fs/2), type= "pass", plane ="z")

# Apply the filter to the data
data_mvc_rf <- data_mvc_rf |> mutate(signal_filtered = filtfilt(bf, signal))
data_mvc_bf <- data_mvc_bf |> mutate(signal_filtered = filtfilt(bf, signal))
data_mvt <- data_mvt |> mutate(signal_bf_filtered = filtfilt(bf, signal_bf), 
                               signal_rf_filtered = filtfilt(bf, signal_rf
                                                            ))
```

## Plot filtered signals
```{r}
gg_mvc_bf_filt <- ggplot(data_mvc_bf, aes(time, signal_filtered)) +
  geom_line(color = "blue") +
  labs(x = "Time", 
       y = "Amplitude (mV)", 
       title = "EMG MVC Biceps Femoris Filtered") +
  theme_light()

gg_mvc_rf_filt <- ggplot(data_mvc_rf, aes(time, signal_filtered)) +
  geom_line(color = "blue") +
  labs(x = "Time", 
       y = "Amplitude (mV)", 
       title = "EMG MVC Rectus Femoris Filtered") +
  theme_light()

gg_mvt_bf_filt <- ggplot(data_mvt, aes(time, signal_bf_filtered)) +
  geom_line(color = "blue") +
  labs(x = "Time", 
       y = "Amplitude (mV)", 
       title = "EMG Movement Biceps Femoris Filtered") +
  theme_light()

gg_mvt_rf_filt <- ggplot(data_mvt, aes(time, signal_rf_filtered)) +
  geom_line(color = "blue") +
  labs(x = "Time", 
       y = "Amplitude (mV)", 
       title = "EMG Movement Rectus Femoris Filtered") +
  theme_light()

gg_mvc_bf_raw / gg_mvc_rf_raw
gg_mvt_bf_raw / gg_mvt_bf_raw
gg_mvc_bf_filt / gg_mvc_rf_filt
gg_mvt_bf_filt / gg_mvt_bf_filt
```

## Amplitude analysis
### Calculate RMS envelope
```{r}
# Compute the power of the signal
data_mvc_bf <- data_mvc_bf |> mutate(signal_power = signal_filtered^2)
data_mvc_rf <- data_mvc_rf |> mutate(signal_power = signal_filtered^2)
data_mvt <- data_mvt |> mutate(signal_bf_power = signal_bf_filtered^2,
                               signal_rf_power = signal_rf_filtered^2
                              )

# Apply a moving window average to smooth the signal


rms_env <- function(power) {
  window_size <- 0.1
  window_size_samples <- window_size*fs
  sqrt(stats::filter(power, rep(1 / window_size_samples, window_size_samples), method = "conv"))
}

data_mvc_bf <- data_mvc_bf |> mutate(signal_rms_env = rms_env(signal_power)) |> na.omit()
data_mvc_rf <- data_mvc_rf |> mutate(signal_rms_env = rms_env(signal_power)) |> na.omit()
data_mvt <- data_mvt |> mutate(signal_bf_rms_env = rms_env(signal_bf_power),
                               signal_rf_rms_env = rms_env(signal_rf_power)) |>
  na.omit()

data_mvc_bf <- data_mvc_bf |> mutate(time = time - min(time))
data_mvc_rf <- data_mvc_rf |> mutate(time = time - min(time))
data_mvt <- data_mvt |> mutate(time = time - min(time))
```


## Normalization and plot normalized RMSE signals
```{r}
# Normalize the signal by dividing by the MVC value
mvc_bf <- max(data_mvc_bf$signal_rms_env)
mvc_rf <- max(data_mvc_rf$signal_rms_env)

data_mvc_bf <- data_mvc_bf |> mutate(signal_normalized = signal_rms_env / mvc_bf)
data_mvc_rf <- data_mvc_rf |> mutate(signal_normalized = signal_rms_env / mvc_rf)
data_mvt <- data_mvt |> mutate(bf_normalized = signal_bf_rms_env / mvc_bf,
                               rf_normalized = signal_rf_rms_env / mvc_rf
                               )
```

## Plot the normalized RMS envelope
```{r}
gg_mvc_bf_rms <- ggplot(data_mvc_bf, aes(time, signal_normalized)) +
  geom_line(color = "blue") +
  labs(x = "Time", 
       y = "Amplitude (mV)", 
       title = "EMG MVC Biceps Femoris Normalized RMS Envelope") +
  theme_light()

gg_mvc_rf_rms <- ggplot(data_mvc_rf, aes(time, signal_normalized)) +
  geom_line(color = "blue") +
  labs(x = "Time", 
       y = "Amplitude (mV)", 
       title = "EMG MVC Rectus Femoris Normalized RMS Envelope") +
  theme_light()

gg_mvt_bf_rms <- ggplot(data_mvt, aes(time, bf_normalized)) +
  geom_line(color = "blue") +
  labs(x = "Time", 
       y = "Amplitude (mV)", 
       title = "EMG Movement Biceps Femoris Normalized RMS Envelope") +
  theme_light()

gg_mvt_rf_rms <- ggplot(data_mvt, aes(time, rf_normalized)) +
  geom_line(color = "blue") +
  labs(x = "Time", 
       y = "Amplitude (mV)", 
       title = "EMG Movement Rectus Femoris Normalized RMS Envelope") +
  theme_light()

gg_mvc_bf_rms / gg_mvc_rf_rms
gg_mvt_bf_rms / gg_mvt_rf_rms
```